- name: Install nginx
  apt: 
    name: nginx
    state: present

- name: Copy configs
  ansible.builtin.copy:
    src: "{{file_location}}/default"
    dest: /etc/nginx/sites-enabled/default

- name: Check that service Nginx is started
  ansible.builtin.service:
    name: nginx
    state: started
    
- name: Enable service nginx
  service:
    name: nginx
    enabled: yes

- name: Reload nginx
  shell: nginx -s reload
